### ISSUE TITLE
Issue when deserializing unicode characters

### ISSUE THREAD

**Issue by NinoScript** [gfx/Swift-PureJsonSerializer#13]
I'm not sure if there is a standard for [Unicode Escape Formats](http://billposer.org/Software/ListOfRepresentations.html) or not, neither do I know if this is a responsibility of PureJsonSerializer, but here I come anyway:

I have a string that's being sent from a backend in ruby, that has characters like this: `\u00e9`
The parseEscapedChar function is assuming the length of such string is anything between 2 and 8 bytes, and ends when a character that can't represent a hex value is found.

So this: `\u00e9r` is understood as `\u{00e9}r` (or `ér`) 
but this: `\u00e9d` is understood as `\u{00e9d}` (or `ຝ`) instead of the expected `\u{00e9}d` (or `éd`)

I'm currently doing a preprocessing step to replace these kinds of characters `\\u([0-9a-f]{4})` with the actual character before feeding it to PureJsonSerializer.

Here's my current code for that preprocessing step in case it's of any use.
``` Swift
private static func deserializeJsonData(data: NSData) throws -> Json {
    let stringData = try String(data: data, encoding: NSUTF8StringEncoding).unwrap()
	// note: unwrap() is a simple extension to optionals that returns the unwrapped value or throws
    
    let regex = try NSRegularExpression(pattern: "\\\\u([0-9a-f]{4})", options: .CaseInsensitive)
    let wholeRange = NSMakeRange(0, stringData.characters.count)
    
    let s = NSMutableString(string: stringData)
    var offset = 0
    regex.enumerateMatchesInString(stringData, options: .WithTransparentBounds, range: wholeRange) { (textCheckingResult, _, _) -> Void in
        guard let result = textCheckingResult else {
            return
        }
        
        var captureRange = result.rangeAtIndex(1)
        captureRange.location += offset
        
        var replacementRange = result.range
        replacementRange.location += offset

        let capture = s.substringWithRange(captureRange)
        guard let unicode = Int32(capture, radix: 16) else {
            return
        }
        
        let replacement = String(format: "%C", unicode)
        s.replaceCharactersInRange(replacementRange, withString: replacement)
        offset += replacement.characters.count - replacementRange.length
    }
    
    let preprocessedString = String(s)
    return try Json.deserialize(preprocessedString)
}
```

It's supposed to replace calls to `try Json.deserialize(data)` in my code.

**Comment by LoganWright** [comment]
@gfx Do you have thoughts on this, I'm not as proficient in unicode stuff

**Comment by gfx** [comment]
It depends on the JSON standard, [RFC 7159](http://tools.ietf.org/html/rfc7159), but preprocessing makes no sense. IMO it should be fixed.

**Comment by NinoScript** [comment]
A quick read of the relevant parts in that standard says that basic characters (up to 16 bits) \u must be followed by a 4 digit hex, and in the case of a surrogate pair (up to 32 bits), it's just two times the \u +4 digits.

BTW, the preprocessing step makes sense to me because I needed a momentary solution meanwhile the correct solution was discussed and implemented, and I shared it just in case someone was in my same position. But I never wanted to suggest adding that to the library. :wink:
