### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by edjiang** [gfx/Swift-PureJsonSerializer#15]
Swift 3 changed the stdlib api and some things on how the core language works. I made a fork and updated Swift-PureJsonSerializer so it compiles on the latest snapshot. 

Not submitting a pull request since I didn't leave Swift 2.2 compatibility, and it seems like you're distributing on more than just SPM. 

Here's a link for reference: https://github.com/edjiang/Swift-PureJsonSerializer (tag 2.0)

**Comment by LoganWright** [comment]
@edjiang Would you mind submitting it as a PR?

**Comment by edjiang** [comment]
Sure.
